apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: 603552922813.dkr.ecr.us-east-1.amazonaws.com/voting_result:b05dd1ee500cff2450cd735aa2d887c0f770544d-test
        name: result
        ports:
        - containerPort: 80
          name: result
